import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  // next-env.d.ts is generated by `next build` and is not ours to lint.
  { ignores: ["node_modules/**", ".next/**", ".vercel/**", "next-env.d.ts"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
